language: java
dist: trusty

addons:
  sonarcloud:
    organization: "testng-team"

env:
  global:
    - GPG_DIR="`pwd`/deploy"

cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8

before_install:
- unset _JAVA_OPTIONS

script:
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn -Prun-its verify

after_success:
  - "$GPG_DIR/publish.sh"
